import { Component, OnInit, Input, Output, EventEmitter } from "@angular/core";

@Component({
  selector: "app-home-nft-detail",
  templateUrl: "./home-nft-detail.component.html",
  styleUrls: ["./home-nft-detail.component.scss"],
})
export class HomeNftDetailComponent implements OnInit {
  products: Array<object> = [
    //bronze
    {
      id: 9,
      position: 1,
      free: 6000,
      collection: "Common",
      name: "RHINO",
      price: 600,
      image: "car1",
      gif: "car1-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car rhino",
    },
    {
      id: 10,
      position: 2,
      free: 12000,
      collection: "Common",
      name: "PANTHER",
      price: 600,
      image: "car2",
      gif: "car2-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car panther",
    },
    {
      id: 11,

      position: 3,
      free: 24000,
      collection: "Common",
      name: "ONYX",
      price: 600,
      image: "car3",
      gif: "car3-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car onyx",
    },
    {
      id: 12,
      position: 4,
      free: 48000,
      collection: "Common",
      name: "ZANDER",
      price: 600,
      image: "car4",
      gif: "car4-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car zander",
    },
    {
      id: 13,
      position: 5,
      free: 96000,
      collection: "Common",
      name: "CYBORG",
      price: 600,
      image: "car5",
      type: "car",
      gif: "car5-animation",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car cyborg",
    },
    {
      id: 14,
      position: 6,
      free: 192000,
      collection: "Common",
      name: "VULCANIC",
      price: 600,
      image: "car6",
      gif: "car6-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car vulcanic",
    },
    {
      id: 15,
      position: 25,
      collection: "Common rare",
      name: "LUNA",
      price: 3600,
      image: "car25",
      gif: "car25-animation",
      type: "car",
      rare: true,
      ability1: 0.6,
      ability2: 6,
      ability3: "Moon",
      amount: [],
      alt: "nft car luna",
    },
    //silver
    {
      id: 16,
      position: 7,
      free: 288000,
      collection: "Super",
      name: "DORIAN",
      price: 1000,
      image: "car7",
      gif: "car7-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car dorian",
    },
    {
      id: 17,
      position: 8,
      free: 432000,
      collection: "Super",
      name: "PANTHER",
      price: 1000,
      image: "car8",
      gif: "car8-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car panther",
    },
    {
      id: 18,
      position: 9,
      free: 648000,
      collection: "Super",
      name: "ONYX",
      price: 1000,
      image: "car9",
      gif: "car9-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car onyx",
    },
    {
      id: 19,
      position: 10,
      free: 972000,
      collection: "Super",
      name: "ZANDER",
      price: 1000,
      image: "car10",
      gif: "car10-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car zander",
    },
    {
      id: 20,
      position: 11,
      free: 1458000,
      collection: "Super",
      name: "PYTHON",
      price: 1000,
      image: "car11",
      gif: "car11-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car python",
    },
    {
      id: 21,
      position: 12,
      free: 2187000,
      collection: "Super",
      name: "VULCANIC",
      price: 1000,
      image: "car12",
      gif: "car12-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car vulcanic",
    },
    {
      id: 22,
      position: 26,
      collection: "Super rare",
      name: "SILVER KNIGHT",
      price: 6000,
      image: "car26",
      gif: "car26-animation",
      type: "car",
      rare: true,
      ability1: 1.98,
      ability2: 12,
      ability3: "Moon",
      amount: [],
      alt: "nft car silver knight",
    },
    //gold
    {
      id: 23,
      position: 13,
      free: 3000000,
      collection: "Epic",
      name: "CYBORG",
      price: 1600,
      image: "car13",
      gif: "car13-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car cyborg",
    },
    {
      id: 24,
      position: 14,
      free: 3600000,
      collection: "Epic",
      name: "RHINO",
      price: 1600,
      image: "car14",
      gif: "car14-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car rhino",
    },
    {
      id: 25,
      position: 15,
      free: 4320000,
      collection: "Epic",
      name: "HYPER",
      price: 1600,
      image: "car15",
      gif: "car15-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car hyper",
    },
    {
      id: 26,
      position: 16,
      free: 5184000,
      collection: "Epic",
      name: "BULL",
      price: 1600,
      image: "car16",
      gif: "car16-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car bull",
    },
    {
      id: 27,
      position: 17,
      free: 6220000,
      collection: "Epic",
      name: "PYTHON",
      price: 1600,
      image: "car17",
      gif: "car17-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car python",
    },
    {
      id: 28,
      position: 18,
      free: 7465000,
      collection: "Epic",
      name: "HITMAN",
      price: 1600,
      image: "car18",
      gif: "car18-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car hitman",
    },
    {
      id: 29,
      position: 27,
      collection: "Epic rare",
      name: "MIDAS",
      price: 9600,
      image: "car27",
      gif: "car27-animation",
      type: "car",
      rare: true,
      ability1: 4.74,
      ability2: 18,
      ability3: "Moon",
      amount: [],
      alt: "nft car midas",
    },
    //platinum
    {
      id: 30,
      position: 19,
      free: 8200000,
      collection: "Legendary",
      name: "HYPER",
      price: 2600,
      image: "car19",
      gif: "car19-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 16172,
      amount: [],
      alt: "nft car hyper",
    },
    {
      id: 31,
      position: 20,
      free: 9000000,
      collection: "Legendary",
      name: "DORIAN",
      price: 2600,
      image: "car20",
      gif: "car20-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 16172,
      amount: [],
      alt: "nft car dorian",
    },
    {
      id: 32,
      position: 21,
      free: 9900000,
      collection: "Legendary",
      name: "VULCANIC",
      price: 2600,
      image: "car21",
      gif: "car21-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 16172,
      amount: [],
      alt: "nft car vulcanic",
    },
    {
      id: 33,
      position: 22,
      free: 10890000,
      collection: "Legendary",
      name: "BULL",
      price: 2600,
      image: "car22",
      gif: "car22-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 16172,
      amount: [],
      alt: "nft car bull",
    },
    {
      id: 34,
      position: 23,
      free: 12000000,
      collection: "Legendary",
      name: "KNOCKOUT",
      price: 2600,
      image: "car23",
      gif: "car23-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 16172,
      amount: [],
      alt: "nft car knockout",
    },
    {
      id: 35,
      position: 24,
      free: 13200000,
      collection: "Legendary",
      name: "LARA",
      price: 2600,
      image: "car24",
      gif: "car24-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 16172,
      amount: [],
      alt: "nft car lara",
    },
    {
      id: 36,
      position: 28,
      collection: "Legendary rare",
      name: "BLUE STORM",
      price: 15600,
      image: "car28",
      gif: "car28-animation",
      type: "car",
      rare: true,
      ability1: 10.25,
      ability2: 24,
      ability3: "Moon",
      amount: [],
      alt: "nft car blue storm",
    },
    {
      id: 71,
      position: 71,
      collection: "Special edition",
      name: "R8",
      price: 150,
      image: "car71",
      gif: "car71-animation",
      type: "car",
      amount: 0,
      alt: "nft car R8",
    },
    {
      id: 72,
      position: 72,
      collection: "Special edition",
      name: "GAZ-13 Caika",
      price: 150,
      image: "car72",
      gif: "car72-animation",
      type: "car",
      amount: 0,
      alt: "nft car GAZ-13 Caika",
    },
    {
      id: 73,
      position: 73,
      collection: "Special edition",
      name: "Formation",
      price: 150,
      image: "car73",
      gif: "car73-animation",
      type: "car",
      amount: 0,
      alt: "nft car Formation",
    },
    {
      id: 37,
      position: 60,
      collection: "Special",
      name: "TESLA",
      price: 50,
      image: "car60",
      type: "car",
      ability3: "8760",
      amount: [],
      alt: "nft car tesla",
    },
    {
      id: 1,
      position: 0,
      collection: "Super",
      name: "Axle",
      price: "100",
      image: "white-trm",
      gif: "white-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Axle",
    },

    {
      id: 2,
      position: 1,
      collection: "Super",
      name: "Flash",
      price: "100",
      image: "red-trm",
      gif: "red-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Flash",
    },
    {
      id: 3,
      position: 2,
      collection: "Super",
      name: "Octane",
      price: "100",
      image: "blue-trm",
      gif: "blue-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Octane",
    },
    {
      id: 4,
      position: 3,
      collection: "Super",
      name: "Punisher",
      price: "100",
      image: "black-trm",
      gif: "black-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Punisher",
    },
    {
      id: 5,
      position: 4,
      collection: "Epic",
      name: "Lady Rich",
      price: "1 000",
      image: "lady-rich",
      gif: "lady-rich-animation",
      type: "racer",
      ability1: "1.5%",
      ability2: "15%",
      rank: "normal",
      amount: [],
      alt: "nft racer Lady Rich",
    },
    {
      id: 6,
      position: 5,
      collection: "Epic",
      name: "Rich Jr.",
      price: "1 000",
      image: "bad-boy",
      gif: "bad-boy-animation",
      type: "racer",
      ability1: "1.5%",
      ability2: "15%",
      rank: "normal",
      amount: [],
      alt: "nft racer Rich Junior",
    },
    {
      id: 7,
      position: 6,
      collection: "Epic",
      name: "Mrs. Rich",
      price: "1 000",
      image: "mrs-rich",
      gif: "mrs-rich-animation",
      type: "racer",
      ability1: "1.5%",
      ability2: "15%",
      rank: "normal",
      amount: [],
      alt: "nft racer Mrs. Rich",
    },
    {
      id: 8,
      position: 7,
      collection: "Legendary",
      name: "Mr. Rich",
      price: "10 000",
      image: "mr-rich",
      gif: "mr-rich-animation",
      type: "racer",
      ability1: "2%",
      ability2: "20%",
      ability3: "18% APY staking",
      rank: "height",
      amount: [],
      alt: "nft racer mr. rich",
    },
    {
      id: 44,
      position: 0,
      type: "bundle",
      name: "DAOMaker",
      link: "@TheDaoMaker",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-dao",
      racer: "dao-maker",
      car: "car41",
      avatar: "dao-avatar",
      back: "dao-back",
    },
    {
      id: 45,
      position: 1,
      type: "bundle",
      name: "Shreyansh Polygon",
      link: "@shreyansh_27",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-polygon",
      racer: "polygon",
      car: "car42",
    },
    {
      id: 46,
      position: 3,
      type: "bundle",
      name: "Kyle Chasse",
      link: "@kyle_chasse",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-kyle",
      racer: "paid",
      car: "car44",
      avatar: "paid-avatar",
      back: "paid-back",
    },
    {
      id: 47,
      position: 4,
      type: "bundle",
      name: "Ash WSB",
      link: "@ashWSBreal",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-ash",
      racer: "ash-wsb",
      car: "car45",
      avatar: "ash-avatar",
      back: "ash-back",
    },
    {
      id: 48,
      position: 5,
      type: "bundle",
      name: "Tehmoonwalker",
      link: "@tehMoonwalkeR",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-tehmoon",
      racer: "tehmoonwalker",
      car: "car46",
      avatar: "tehmoon-avatar",
      back: "tehmoon-back",
    },

    {
      id: 49,
      position: 6,
      type: "bundle",
      name: "Parabolic Guy",
      link: "@GoingParabolic",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-parabolic",
      racer: "parabolic-guy",
      car: "car47",
      avatar: "parabolic-avatar",
      back: "parabolic-back",
    },
    {
      id: 50,
      position: 9,
      type: "bundle",
      name: "Altcoin Buzz",
      link: "@Altcoinbuzzio",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-altcoin",
      racer: "altcoin-buzz",
      car: "car50",
      avatar: "altcoin-avatar",
      back: "altcoin-back",
    },
    {
      id: 51,
      position: 10,
      type: "bundle",
      name: "Cryptowizard",
      link: "@CryptoWizardd",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-wizard",
      racer: "cryptowizard",
      car: "car51",
      avatar: "cryptowizard-avatar",
      back: "cryptowizard-back",
    },
    {
      id: 52,
      position: 11,
      type: "bundle",
      name: "Kucoin",
      link: "@kucoincom",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-kucoin",
      racer: "kucoin",
      car: "car52",
      avatar: "cryptowizard-avatar",
      back: "cryptowizard-back",
    },
    {
      id: 53,
      position: 13,
      type: "bundle",
      name: "QuickSwap",
      link: "@QuickswapDEX",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-quickswap",
      racer: "quickswap",
      car: "car53",
      avatar: "",
      back: "",
    },
    {
      id: 54,
      position: 14,
      type: "bundle",
      name: "Tech Giants",
      link: "@Crypto_giants",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-techgiants",
      racer: "techgiants",
      car: "car54",
      avatar: "",
      back: "",
    },
    {
      id: 55,
      position: 15,
      type: "bundle",
      name: "Venly",
      link: "@Venly_io",
      nft: 10,
      staking: 6,
      reward: 0.1,
      price: 1000,
      pieces: 100,
      yearly: 8760,
      image: "bundle-venly",
      racer: "venly",
      car: "car55",
      avatar: "",
      back: "",
    },
  ];
  infoRoi = false;
  infoRoiYearly = false;
  position: number;

  displayArray = [];
  @Input() assetType = "bundle";
  @Input() assetId = 1;
  @Input() assetPosition = 1;
  @Output() modalActive = new EventEmitter<number>();
  @Output() marketState = new EventEmitter<number>();

  noGifActive = true;
  gifName = "";
  animationActive = false;
  timer = null;

  timer2 = null;

  constructor() {}

  ngOnInit() {
    this.resolveShowAsset();
  }

  showAnimation() {
    this.animationActive = false;
    this.noGifActive = true;
    this.gifName = "none1";
    this.timer2 = setTimeout(() => {
      this.gifName = "black-trm-animation";
      this.animationActive = true;
      this.noGifActive = false;
    }, 1);
    this.timer = setTimeout(() => {
      this.animationActive = false;
      this.gifName = "none1";
      this.noGifActive = true;
    }, 6500);
  }

  activateAnimation() {
    clearTimeout(this.timer2);
    clearTimeout(this.timer);
    this.showAnimation();
  }

  resolveShowAsset() {
    this.displayArray = this.products.filter(
      (asset) => asset["id"] === this.assetId
    );
    this.position = this.displayArray[0]["position"];
  }

  showBuyModal() {
    this.marketState.emit(3);
  }

  showModal(p) {
    this.modalActive.emit(p);
  }
  back() {
    {
      this.marketState.emit(1);
    }
  }
}
