import { Component, OnInit, Input, Output, EventEmitter } from "@angular/core";

@Component({
  selector: "app-my-nft-detail",
  templateUrl: "./my-nft-detail.component.html",
  styleUrls: ["./my-nft-detail.component.scss"],
})
export class MyNftDetailComponent implements OnInit {
  noGifActive = true;
  gifName = "";
  animationActive = false;
  displayArray = [];
  modalActive: any;
  infoRoi = false;
  infoRoiYearly = false;
  @Input() assetType = "car";
  @Input() assetId = 11;
  @Input() owned;

  @Output() marketState = new EventEmitter<number>();
  products: Array<object> = [
    //bronze
    {
      id: 20,
      position: 1,
      free: 6000,
      collection: "Common",
      name: "RHINO",
      price: 600,
      image: "car1",
      gif: "car1-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car rhino",
    },
    {
      id: 21,
      position: 2,
      free: 12000,
      collection: "Common",
      name: "PANTHER",
      price: 600,
      image: "car2",
      gif: "car2-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car panther",
    },
    {
      id: 22,
      position: 3,
      free: 24000,
      collection: "Common",
      name: "ONYX",
      price: 600,
      image: "car3",
      gif: "car3-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car onyx",
    },
    {
      id: 23,
      position: 4,
      free: 48000,
      collection: "Common",
      name: "ZANDER",
      price: 600,
      image: "car4",
      gif: "car4-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car zander",
    },
    {
      id: 24,
      position: 5,
      free: 96000,
      collection: "Common",
      name: "CYBORG",
      price: 600,
      image: "car5",
      type: "car",
      gif: "car5-animation",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car cyborg",
    },
    {
      id: 25,
      position: 6,
      free: 192000,
      collection: "Common",
      name: "VULCANIC",
      price: 600,
      image: "car6",
      gif: "car6-animation",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      amount: [],
      alt: "nft car vulcanic",
    },
    {
      id: 26,
      position: 25,
      collection: "Common rare",
      name: "LUNA",
      price: 3600,
      image: "car25",
      gif: "car25-animation",
      type: "car",
      rare: true,
      ability1: 0.6,
      ability2: 6,
      ability3: "Moon",
      amount: [],
      alt: "nft car luna",
    },
    //silver
    {
      id: 27,
      position: 7,
      free: 288000,
      collection: "Super",
      name: "DORIAN",
      price: 1000,
      image: "car7",
      gif: "car7-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car dorian",
    },
    {
      id: 28,
      position: 8,
      free: 432000,
      collection: "Super",
      name: "PANTHER",
      price: 1000,
      image: "car8",
      gif: "car8-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car panther",
    },
    {
      id: 29,
      position: 9,
      free: 648000,
      collection: "Super",
      name: "ONYX",
      price: 1000,
      image: "car9",
      gif: "car9-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car onyx",
    },
    {
      id: 30,
      position: 10,
      free: 972000,
      collection: "Super",
      name: "ZANDER",
      price: 1000,
      image: "car10",
      gif: "car10-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car zander",
    },
    {
      id: 31,
      position: 11,
      free: 1458000,
      collection: "Super",
      name: "PYTHON",
      price: 1000,
      image: "car11",
      gif: "car11-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car python",
    },
    {
      id: 32,
      position: 12,
      free: 2187000,
      collection: "Super",
      name: "VULCANIC",
      price: 1000,
      image: "car12",
      gif: "car12-animation",
      type: "car",
      ability1: 0.33,
      ability2: 12,
      ability3: 10526,
      amount: [],
      alt: "nft car vulcanic",
    },
    {
      id: 33,
      position: 26,
      collection: "Super rare",
      name: "SILVER KNIGHT",
      price: 6000,
      image: "car26",
      gif: "car26-animation",
      type: "car",
      rare: true,
      ability1: 1.98,
      ability2: 12,
      ability3: "Moon",
      amount: [],
      alt: "nft car silver knight",
    },
    //gold
    {
      id: 34,
      position: 13,
      free: 3000000,
      collection: "Epic",
      name: "CYBORG",
      price: 1600,
      image: "car13",
      gif: "car13-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car cyborg",
    },
    {
      id: 35,
      position: 14,
      free: 3600000,
      collection: "Epic",
      name: "RHINO",
      price: 1600,
      image: "car14",
      gif: "car14-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car rhino",
    },
    {
      id: 36,
      position: 15,
      free: 4320000,
      collection: "Epic",
      name: "HYPER",
      price: 1600,
      image: "car15",
      gif: "car15-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car hyper",
    },
    {
      id: 37,
      position: 16,
      free: 5184000,
      collection: "Epic",
      name: "BULL",
      price: 1600,
      image: "car16",
      gif: "car16-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car bull",
    },
    {
      id: 38,
      position: 17,
      free: 6220000,
      collection: "Epic",
      name: "PYTHON",
      price: 1600,
      image: "car17",
      gif: "car17-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car python",
    },
    {
      id: 39,
      position: 18,
      free: 7465000,
      collection: "Epic",
      name: "HITMAN",
      price: 1600,
      image: "car18",
      gif: "car18-animation",
      type: "car",
      ability1: 0.79,
      ability2: 18,
      ability3: 13140,
      amount: [],
      alt: "nft car hitman",
    },
    {
      id: 40,
      position: 27,
      collection: "Epic rare",
      name: "MIDAS",
      price: 9600,
      image: "car27",
      gif: "car27-animation",
      type: "car",
      rare: true,
      ability1: 4.74,
      ability2: 18,
      ability3: "Moon",
      amount: [],
      alt: "nft car midas",
    },
    //platinum
    {
      id: 41,
      position: 19,
      free: 8200000,
      collection: "Legendary",
      name: "HYPER",
      price: 2600,
      image: "car19",
      gif: "car19-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 12123,
      amount: [],
      alt: "nft car hyper",
    },
    {
      id: 42,
      position: 20,
      free: 9000000,
      collection: "Legendary",
      name: "DORIAN",
      price: 2600,
      image: "car20",
      gif: "car20-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 12123,
      amount: [],
      alt: "nft car dorian",
    },
    {
      id: 43,
      position: 21,
      free: 9900000,
      collection: "Legendary",
      name: "VULCANIC",
      price: 2600,
      image: "car21",
      gif: "car21-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 12123,
      amount: [],
      alt: "nft car vulcanic",
    },
    {
      id: 44,
      position: 22,
      free: 10890000,
      collection: "Legendary",
      name: "BULL",
      price: 2600,
      image: "car22",
      gif: "car22-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 12123,
      amount: [],
      alt: "nft car bull",
    },
    {
      id: 45,
      position: 23,
      free: 12000000,
      collection: "Legendary",
      name: "KNOCKOUT",
      price: 2600,
      image: "car23",
      gif: "car23-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 12123,
      amount: [],
      alt: "nft car knockout",
    },
    {
      id: 46,
      position: 24,
      free: 13200000,
      collection: "Legendary",
      name: "LARA",
      price: 2600,
      image: "car24",
      gif: "car24-animation",
      type: "car",
      ability1: 1.71,
      ability2: 24,
      ability3: 12123,
      amount: [],
      alt: "nft car lara",
    },
    {
      id: 47,
      position: 28,
      collection: "Legendary rare",
      name: "BLUE STORM",
      price: 15600,
      image: "car28",
      gif: "car28-animation",
      type: "car",
      rare: true,
      ability1: 10.25,
      ability2: 24,
      ability3: "Moon",
      amount: [],
      alt: "nft car blue storm",
    },
    {
      id: 48,
      collection: "Special",
      name: "DAOMaker",
      link: "@TheDaoMaker",
      image: "car41",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car DAOMaker",
    },
    {
      id: 49,
      collection: "Special",
      name: "Shreyansh Polygon",
      link: "@shreyansh_27",
      image: "car42",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Cryptowizard",
    },
    {
      id: 50,
      collection: "Special",
      name: "Kyle Chasse",
      link: "@kyle_chasse",
      image: "car44",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Kyle Chasse",
    },
    {
      id: 51,
      collection: "Special",
      name: "Ash WSB",
      link: "@ashWSBreal",
      image: "car45",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Ash WSB",
    },
    {
      id: 52,
      collection: "Special",
      name: "Tehmoonwalker",
      link: "@tehMoonwalkeR",
      image: "car46",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Tehmoonwalker",
    },
    {
      id: 53,
      collection: "Special",
      name: "Parabolic Guy",
      link: "@GoingParabolic",
      image: "car47",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Parabolic Guy",
    },
    {
      id: 54,
      collection: "Special",
      name: "Altcoin Buzz",
      link: "@Altcoinbuzzio",
      image: "car50",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Altcoin Buzz",
    },
    {
      id: 55,
      collection: "Special",
      name: "Cryptowizard",
      link: "@CryptoWizardd",
      image: "car51",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Cryptowizard",
    },
    {
      id: 56,
      collection: "Special",
      name: "Kucoin",
      link: "@kucoincom",
      image: "car52",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Kucoin",
    },
    {
      id: 57,
      collection: "Special",
      name: "QuickSwap",
      link: "@QuickswapDEX",
      image: "car53",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car QuickSwap",
    },
    {
      id: 58,
      collection: "Special",
      name: "Tech Giants",
      link: "@Crypto_giants",
      image: "car54",
      type: "car",
      ability1: 0.1,
      ability2: 6,
      ability3: 8760,
      rank: "low",
      amount: [],
      alt: "nft car Tech Giants",
    },
    {
      id: 60,
      price: 50,
      name: "TESLA",
      image: "car60",
      type: "car",
      rank: "low",
      ability3: 8760,
      amount: [],
      alt: "nft car Tesla",
    },
    //RACERS
    {
      id: 1,
      collection: "Super",
      name: "Axle",
      price: 100,
      image: "white-trm",
      gif: "white-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Axle",
    },

    {
      id: 2,
      collection: "Super",
      name: "Flash",
      price: 100,
      image: "red-trm",
      gif: "red-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Flash",
    },
    {
      id: 3,
      collection: "Super",
      name: "Octane",
      price: 100,
      image: "blue-trm",
      gif: "blue-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Octane",
    },
    {
      id: 4,
      collection: "Super",
      name: "Punisher",
      price: 100,
      image: "black-trm",
      gif: "black-trm-animation",
      type: "racer",
      ability1: "1%",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Punisher",
    },
    {
      id: 5,
      collection: "Epic",
      name: "Lady Rich",
      price: 1000,
      image: "lady-rich",
      gif: "lady-rich-animation",
      type: "racer",
      ability1: "1.5%",
      ability2: "15%",
      rank: "normal",
      amount: [],
      alt: "nft racer Lady Rich",
    },
    {
      id: 6,
      collection: "Epic",
      name: "Rich Jr.",
      price: 1000,
      image: "bad-boy",
      gif: "bad-boy-animation",
      type: "racer",
      ability1: "1.5%",
      ability2: "15%",
      rank: "normal",
      amount: [],
      alt: "nft racer Rich Junior",
    },
    {
      id: 7,
      collection: "Epic",
      name: "Mrs. Rich",
      price: 1000,
      image: "mrs-rich",
      gif: "mrs-rich-animation",
      type: "racer",
      ability1: "1.5%",
      ability2: "15%",
      rank: "normal",
      amount: [],
      alt: "nft racer Mrs. Rich",
    },
    {
      id: 8,
      collection: "Legendary",
      name: "Mr. Rich",
      price: 10000,
      image: "mr-rich",
      gif: "mr-rich-animation",
      type: "racer",
      ability1: "2%",
      ability2: "20%",
      ability3: "18% APY staking",
      rank: "height",
      amount: [],
      alt: "nft racer mr. rich",
    },
    {
      id: 9,
      collection: "Special",
      name: "DAOMaker",
      link: "@TheDaoMaker",
      image: "dao-maker",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer DAOMaker",
    },
    {
      id: 10,
      collection: "Special",
      name: "Shreyansh Polygon",
      link: "@shreyansh_27",
      image: "polygon",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Polygon",
    },
    {
      id: 11,
      collection: "Special",
      name: "Kyle Chasse",
      link: "@kyle_chasse",
      image: "paid",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Kyle Chasse",
    },
    {
      id: 12,
      collection: "Special",
      name: "Ash WSB",
      link: "@ashWSBreal",
      image: "ash-wsb",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Ash WSB",
    },
    {
      id: 13,
      collection: "Special",
      name: "Tehmoonwalker",
      link: "@tehMoonwalkeR",
      image: "tehmoonwalker",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Tehmoonwalker",
    },
    {
      id: 14,
      collection: "Special",
      name: "Parabolic Guy",
      link: "@GoingParabolic",
      image: "parabolic-guy",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Parabolic Guy",
    },
    {
      id: 15,
      collection: "Special",
      name: "Altcoin Buzz",
      link: "@Altcoinbuzzio",
      image: "altcoin-buzz",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Altcoin Buzz",
    },
    {
      id: 16,
      collection: "Special",
      name: "Cryptowizard",
      link: "@CryptoWizardd",
      image: "cryptowizard",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Cryptowizard",
    },
    {
      id: 17,
      collection: "Special",
      name: "Kucoin",
      link: "@kucoincom",
      image: "kucoin",
      type: "racer",
      ability2: "10%",
      rank: "low",
      amount: [],
      alt: "nft racer Kucoin",
    },
  ];

  constructor() {}

  ngOnInit() {
    this.resolveShowAsset();
  }

  resolveShowAsset() {
    this.displayArray = this.products.filter(
      (asset) => asset["id"] === this.assetId
    );
  }
  closeModal() {
    this.modalActive = false;
  }
  showModal(p) {
    this.modalActive = p;
  }
  backToProducts() {
    this.marketState.emit(1);
  }
  timer = null;
  timer2 = null;
  showAnimation() {
    this.animationActive = false;
    this.noGifActive = true;
    this.gifName = "none1";
    this.timer2 = setTimeout(() => {
      this.gifName = "black-trm-animation";
      this.animationActive = true;
      this.noGifActive = false;
    }, 1);
    this.timer = setTimeout(() => {
      this.animationActive = false;
      this.gifName = "none1";
      this.noGifActive = true;
    }, 6500);
  }

  activateAnimation() {
    clearTimeout(this.timer2);
    clearTimeout(this.timer);
    this.showAnimation();
  }
}
